### ISSUE TITLE
进度目标

### ISSUE THREAD

**Issue by linstein** [DvcLAB/JupyterLab-Image#10]
- [x] 1. keycloak登录（已完成）
- [x] 2. JupyterLab镜像获取使用  
  - [x] 2.1 测试沣东docker registry
  - [x] 2.2 上传镜像文件
  - [x] 2.3 版本号管理
             [镜像版本记录](https://docs.google.com/document/d/1fP2XAyRxYj933xypraYIhf8k4as7zh3hHD2Udvi4Fpk/edit#heading=h.8ppnmjc3p29z)
  - [x] 2.4  简化命令，执行文件（windows,mac,linux）
        win10环境下运行docker也需要linux环境，因此主要考虑linux下的执行脚本
  - [x] 2.5  任何系统，有无GPU都可使用
- [x] 3. 加载项目
  - [x] 3.1 配置文件设置
  - [x] 3.2 git命令（示例）
          [Git项目加载](https://docs.google.com/document/d/1fP2XAyRxYj933xypraYIhf8k4as7zh3hHD2Udvi4Fpk/edit#heading=h.2wg6xrjuji0t)
  - [x] 3.3 示例项目列表，放在 dvclab下
          [项目列表](https://docs.google.com/spreadsheets/d/14nJfAfpPIcYmjs2nND6M2BRsRLJ7EmPOnxPPFUm-PKM/edit#gid=601850367)
- [x] 4. 数据集挂载
  - [x] 4.1  s3数据集列表
          [数据集列表](https://docs.google.com/spreadsheets/d/14nJfAfpPIcYmjs2nND6M2BRsRLJ7EmPOnxPPFUm-PKM/edit#gid=6417116)
  - [x] 4.2  数据集权限（public_read，只有管理员可以修改文件）
  - [x] 4.3  不需要AK/SK即可挂载
- [x] 5. 综合命令，加载项目数据集 
           结合上面数据集加载和git项目加载命令即可

**Comment by linstein** [comment]
3.1完成

**Comment by linstein** [comment]
docker registry上传报错
![image](https://user-images.githubusercontent.com/38755884/109300422-76850a00-7871-11eb-8b22-6808407ff668.png)
参考：
[docker registry and nginx](https://stackoverflow.com/questions/50613532/docker-registry-and-nginx-entity-too-large-client-max-body-size-has-no-effec)
需要设置nginx中http的参数client_max_body_size 0;

**Comment by linstein** [comment]
数据集的公开可读挂载步骤：
1. 将创建的bucket的acl设置为acl_public
`s3cmd setacl --acl-public  s3://mnist`
2. s3fs挂载时设置bucket为public_bucket
`s3fs mnist /workspace/data  -o public_bucket=1  -o sigv2 -o use_path_request_style  -o url=http://10.0.5.30:80 -o default_acl=public-read`

**Comment by JJLAAA** [comment]
> docker registry上传报错
> ![image](https://user-images.githubusercontent.com/38755884/109300422-76850a00-7871-11eb-8b22-6808407ff668.png)
> 参考：
> [docker registry and nginx](https://stackoverflow.com/questions/50613532/docker-registry-and-nginx-entity-too-large-client-max-body-size-has-no-effec)
> 需要设置nginx中http的参数client_max_body_size 0;
> 已解决

**Comment by JJLAAA** [comment]
> docker registry上传报错
> ![image](https://user-images.githubusercontent.com/38755884/109300422-76850a00-7871-11eb-8b22-6808407ff668.png)
> 参考：
> [docker registry and nginx](https://stackoverflow.com/questions/50613532/docker-registry-and-nginx-entity-too-large-client-max-body-size-has-no-effec)
> 需要设置nginx中http的参数client_max_body_size 0;
> 已解决

**Comment by linstein** [comment]
1. 在pipreqs扫描安装依赖库时，无法安装所有被import的库

2. 以cv2为例，pipreqs无法自动安装open-cv库，需要用户在环境中自己安装
参考：
[1. pipreqs not capturing all imports](https://github.com/bndr/pipreqs/issues/127)

**Comment by linstein** [comment]
fd11机器nvidia-smi报错：Failed to initialize NVML: Driver/library version mismatch
![image](https://user-images.githubusercontent.com/38755884/109382003-ab986780-7918-11eb-90ed-f5bb3ea9ea83.png)

**Comment by linstein** [comment]
docker pull 拉取单层layer较大的镜像时出现Unexpected EOF错误，但拉取普通的小镜像没有问题
